src/Entity/Employer.php
<?php

namespace App\Entity;

use App\Repository\EmployerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployerRepository::class)]
class Employer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\Column(type: 'date')]
    private $dateNais;

    #[ORM\Column(type: 'text')]
    private $Image;

    #[ORM\Column(type: 'integer')]
    private $tel;

    #[ORM\Column(type: 'string', length: 255)]
    private $email;

    #[ORM\Column(type: 'string', length: 255)]
    private $adresse;

    #[ORM\Column(type: 'float')]
    private $salaire;

    #[ORM\Column(type: 'text', nullable: true)]
    private $cv;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'employers')]
    private $User;

    #[ORM\ManyToOne(targetEntity: Department::class, inversedBy: 'Employers')]
    private $department;

    #[ORM\OneToMany(mappedBy: 'Employers', targetEntity: Prime::class,fetch: "EAGER")]
    private $primes;
/*
    public function __construct()
    {
        $this->primes = new ArrayCollection();
    }
*/
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNais(): ?\DateTimeInterface
    {
        return $this->dateNais;
    }

    public function setDateNais(\DateTimeInterface $dateNais): self
    {
        $this->dateNais = $dateNais;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getTel(): ?int
    {
        return $this->tel;
    }

    public function setTel(int $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getSalaire(): ?float
    {
        return $this->salaire;
    }

    public function setSalaire(float $salaire): self
    {
        $this->salaire = $salaire;

        return $this;
    }

    public function getCv(): ?string
    {
        return $this->cv;
    }

    public function setCv(?string $cv): self
    {
        $this->cv = $cv;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->department;
    }

    public function setDepartment(?Department $department): self
    {
        $this->department = $department;

        return $this;
    }
    /**
     * @return Collection<int, Prime>
     */
    public function getPrimes(): Collection
    {
        return $this->primes;
    }
    public function addPrime(Prime $prime): self
    {
        if (!$this->primes->contains($prime)) {
            $this->primes[] = $prime;
            $prime->setEmployers($this);
        }

        return $this;
    }

    public function removePrime(Prime $prime): self
    {
        if ($this->primes->removeElement($prime)) {
            // set the owning side to null (unless already changed)
            if ($prime->getEmployers() === $this) {
                $prime->setEmployers(null);
            }
        }

        return $this;
    }
}

templates/element/dashbord/header.html.twig
{% for flashMessage in app.session.flashbag.get('error') %}

    <button class="btn btn-danger">{{ flashMessage }}</button>

{% endfor %}

templates/element/dashbord/sidebar.html.twig
<div class="sidebar-wrapper">
    <div class="user">
        <div class="photo">
        <img src="{{ asset ('/uploads/images/' ~  app.user.image) }}" />
        </div>
        <div class="user-info">
        <a data-toggle="collapse" href="#collapseExample" class="username">
            <span>
            {{ app.user.username }}
            <b class="caret"></b>
            </span>
        </a>
        <div class="collapse" id="collapseExample">
            <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="#">
                <span class="sidebar-mini"> L </span>
                <span class="sidebar-normal"> Logout </span>
                </a>
            </li>
            </ul>
        </div>
        </div>
    </div>
    <ul class="nav">
        <li class="nav-item active ">
         {% if (is_granted('ROLE_RESPONSABLE_RH') or is_granted('ROLE_ADMIN') ) %}
            <a class="nav-link" href="{{path('gestion_session_recrutement')}}">
                <i class="material-icons">dashboard</i>
                <p> Dashboard </p>
            </a>
        </li>
        {% endif %}
        {% if is_granted('ROLE_ADMIN')  or is_granted('ROLE_ADMIN') %}
        <li class="nav-item ">
        <a class="nav-link" href="{{path('app_gestionuser')}}">
            <i class="fa fa-user"></i>
            <p> Gestion Users </p>
        </a>
        </li>
        {% endif %}
         {% if is_granted('ROLE_RESPONSABLE_LOGISTIQUE') or is_granted('ROLE_ADMIN') %}
        <li class="nav-item ">
        <a class="nav-link" href="{{path('app_gestionchauffeur')}}">
            <i class="fa fa-truck"></i>
            <p> Gestion Chauffeurs </p>
        </a>
        </li>
        
        <li class="nav-item ">
        <a class="nav-link" href="{{path('app_gestionvoyages')}}">
            <i class="fa fa-plane"></i>
            <p> Gestion Voyages </p>
        </a>
        </li>
        {% endif %}
         {% if is_granted('ROLE_RESPONSABLE_STOCK') or is_granted('ROLE_ADMIN') %}
        <li class="nav-item ">
        <a class="nav-link" href="{{path('app_gestionequipements')}}">
            <i class="fa fa-dropbox"></i>
            <p> Gestion Equipements </p>
        </a>
        </li>
        {% endif %}
         {% if is_granted('ROLE_RESPONSABLE_RH') or is_granted('ROLE_ADMIN')%}
        <li class="nav-item ">
        <a class="nav-link" href="{{path('app_gestiondepartements')}}">
            <i class="fa fa-building"></i>
            <p> Gestion Departement </p>
        </a>
        </li>
       
        <li class="nav-item ">
        <a class="nav-link" href="{{path('app_gestionprimes')}}">
            <i class="fa fa-gift"></i>
            <p> Gestion Primes </p>
        </a>
        </li>
        
        <li class="nav-item ">
        <a class="nav-link" href="{{path('app_gestionemployees')}}">
            <i class="fa fa-users"></i>
            <p> Gestion Employees </p>
        </a>
        </li>
        {% endif %}
    </ul>
    </div>